export const ADMIN_ACTIONS = {
  GET_ALL_APPLICATIONS: 'GET_ALL_APPLICATIONS',
  SET_ALL_APPLICATIONS: 'SET_ALL_APPLICATIONS',
  SAVE_COMMENTS_AND_STATUS: 'SAVE_COMMENTS_AND_STATUS'
};

export const getAllApplications = () => ({
  type: ADMIN_ACTIONS.GET_ALL_APPLICATIONS,
});
