export const ADMIN_ACTIONS = {
  GET_ALL_APPLICATIONS: 'GET_ALL_APPLICATIONS',
  SET_ALL_APPLICATIONS: 'SET_ALL_APPLICATIONS',
};

export const getAllApplications = () => ({
  type: ADMIN_ACTIONS.GET_ALL_APPLICATIONS,
});
